language: objective-c
osx_image: xcode8.3
cache:
  directories:
  - Carthage
before_install:
  - travis_wait 40 carthage bootstrap --no-use-binaries --platform iOS --cache-builds
script:
  - swiftlint
  - xcodebuild -scheme Graviton -project Graviton.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' build test
