language: objective-c
osx_image: xcode8.3
before_script:
  - carthage bootstrap
script:
  - xcodebuild -scheme Graviton -project Graviton.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' build test
