language: objective-c
osx_image: xcode9

cache:
  directories:
  - Carthage
before_install:
  - brew install git-lfs
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - git lfs pull
  - travis_wait 40 carthage bootstrap --no-use-binaries --platform iOS --cache-builds
before_script:
  - swiftlint
script:
  - xcodebuild -scheme Graviton -project Graviton.xcodeproj -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' build test
